### ISSUE TITLE
Change Base url

### ISSUE THREAD

**Issue by ahr1384** [def-studio/telegraph#133]
Hello
I have (self host) in server
and I use http://localhost:8000 instead of https://api.telegram.org
and I need to a method in send message, send document &...
before method send()
that I can specify the base url method
And I can specify its default value in config
this method just change the base url 
Thanks

**Comment by ahr1384** [comment]
#137

**Comment by fabio-ivona** [comment]
implemented

**Comment by ahr1384** [comment]
how to use setBaseUrl() for send custom ?? @fabio-ivona

**Comment by fabio-ivona** [comment]
If you have just one url, just put it in telegraph.php configuration file

Otherwise you can set it while sending the message as any other methods

**Comment by ahr1384** [comment]
Yes, I understand, thank you: @fabio-ivona 
But the problem is that I cannot use it in the store method
I want to change the address to download the file so that I can download up to 2 GB

**Comment by ahr1384** [comment]
It is good if you create a field for store() in the config
To be used only for the store
Or, for example, just to send a message or send a file

**Comment by fabio-ivona** [comment]
It is not planned, for now, sorry

**Comment by ahr1384** [comment]
@fabio-ivona 
This was one of the reasons for opening the issue
There is no way to add this item?
I need it very much

**Comment by fabio-ivona** [comment]
It is not worth to have a dirty code when you can do this:

Telegraph::setBaseUrl('http....')->store($file)

instead of 

Telegraph::store($file, 'http....')

**Comment by ahr1384** [comment]
@fabio-ivona store() in TelegrphBot but we dont access setBaseUrl() in TelegraphBot

**Comment by ahr1384** [comment]
and we dont use 
![image](https://user-images.githubusercontent.com/87445571/187269562-3db76d06-a000-4e46-b8e3-286779829bb5.png)
before message()

**Comment by fabio-ivona** [comment]
in v1.18 you can call ->setBaseUrl() from bot and chat models

**Comment by ahr1384** [comment]
Thanks
but you must 
![image](https://user-images.githubusercontent.com/87445571/187465045-21bdc1bb-975b-4fd5-9b1c-bba0dbcf5e2b.png)
/file/bot
for store and tg file handling...

**Comment by ahr1384** [comment]
@fabio-ivona
