### ISSUE TITLE
Handle unknown commands

### ISSUE THREAD

**Issue by shareef1989** [def-studio/telegraph#150]
Hi,

I tried to handle the unknown commands but I couldn't, could you please tell me if that possible and how?

**Comment by fabio-ivona** [comment]
We just implemented and are under testing, will release it tomorrow

**Comment by fabio-ivona** [comment]
@shareef1989 implemented in https://github.com/def-studio/telegraph/pull/151

will be released today

**Comment by shareef1989** [comment]
BIG THANKS @fabio-ivona for the rapid response!
