### ISSUE TITLE
Requesting Methods

### ISSUE THREAD

**Issue by pm-12** [def-studio/telegraph#162]
- [x] createChatInviteLink
- [x] getChatMemberCount
- [x] setChatPermissions
- [x] promoteChatMember

Would be helpful to have those too.

thanks!

**Comment by fabio-ivona** [comment]
invite links methods implemented in #163

**Comment by fabio-ivona** [comment]
chat member count implemented in #164

**Comment by fabio-ivona** [comment]
chat permissions implemented in #165

**Comment by fabio-ivona** [comment]
chat members management implemented in #166
