### ISSUE TITLE
handleChatMemberJoined method does not work

### ISSUE THREAD

**Issue by Odilbukh** [def-studio/telegraph#341]
I have copied and pasted the code from documentation:
```
protected function handleChatMemberJoined(User $member): void
    {
        $this->chat->html("Welcome {$member->firstName()}")->send();
    }
    
```

But when new telegram user clicks to start to bot handleChatMemberJoined method does not work. Maybe it works in other command (not on /start), IDK

I want register all new users and store their data in DB.

**Comment by fabio-ivona** [comment]
Hi, where did you pasted the code?
