### ISSUE TITLE
Chat Type Group and Commands

### ISSUE THREAD

**Issue by nacr** [def-studio/telegraph#47]
👋 

Thank you for all the work 👍 

regarding this "issue" I don't believe it to be an issue but more of an enhancement.

in a chat group if you do /command all will work but in groups you can have lots of bots with the /start command and doing this will make all of them respond.

Normally one does this /command@my_test_bot but for know the implementation will not respond to this command

Giving the following log message:

```
local.ERROR: No Telegram Webhook handler defined for received command@my_test_bot: command@my_test_bot
```

Once more thank you for your work.

**Comment by fabio-ivona** [comment]
Hi!

thanks for the tip, I think I can easily fix it in a bit, will keep you updated!
