### ISSUE TITLE
Unknown command when in groups

### ISSUE THREAD

**Issue by nacr** [def-studio/telegraph#51]
👋 

The solution in #47 works very well 👍 

But it raises an issue.

When any command is used in the group that does not exist in our bot it will respond with ```Unknown command```

this would be expected if one uses the command like ```/command@my_super_bot```but I don't believe it's the best way when one is just using ```/command```

Thank you for all the work ❤️

**Comment by fabio-ivona** [comment]
I think you're right, the first use of this package (our internal app) didn't allow multiple bots on same chat, so an error is raised

but I think it's more consistent to simply ignore the message if it doesn't match with a public method of the WebhookHandler

will issue a fix in a few minutes

**Comment by nacr** [comment]
Tks m8

**Comment by fabio-ivona** [comment]
fixed in v1.5.0

along with it, you'll found a TelegraphBot method to register your commands in telegram: 

![image](https://user-images.githubusercontent.com/8792274/157654100-fd040313-a933-4b2d-804d-df858016c1c0.png)

**Comment by nacr** [comment]
> fixed in v1.5.0
> 
> along with it, you'll found a TelegraphBot method to register your commands in telegram:
> 
> ![image](https://user-images.githubusercontent.com/8792274/157654100-fd040313-a933-4b2d-804d-df858016c1c0.png)

Yes 🤟 that one will be very handy 👍
