### ISSUE TITLE
Handle all type of webhook messages updates (medias)

### ISSUE THREAD

**Issue by gausoft** [def-studio/telegraph#71]
Hello, thanks for this amazing package. 
Do you plan to add support for any other messages (medias) retrieving by the bot throughout Webhook?
We can actually get only text message

Thanks

**Comment by fabio-ivona** [comment]
Hi! We are planning to do it in the next releases!

**Comment by fabio-ivona** [comment]
@gausoft we are releasing this feature right now :rocket:

**Comment by gausoft** [comment]
Thanks :fire: :star_struck:
