### ISSUE TITLE
Delete Webhook

### ISSUE THREAD

**Issue by mikerockett** [def-studio/telegraph#79]
The documentation makes reference to delete a webhook, but the functionality for this isn’t available.

**Comment by fabio-ivona** [comment]
We are releasing it in a few hours, docs were updated too early, sorry

**Comment by mikerockett** [comment]
No problem, thanks!

**Comment by fabio-ivona** [comment]
Released in v1.11 😉

**Comment by mikerockett** [comment]
Thank you 👍🏻
