### ISSUE TITLE
message inline

### ISSUE THREAD

**Issue by aestrada2796** [def-studio/telegraph#90]
How or when can you use the functionality of telegram online messages

**Comment by fabio-ivona** [comment]
Hi, I'm not sure to have understood your question, could you elaborate please?

**Comment by aestrada2796** [comment]
https://core.telegram.org/bots/inline.

To enable inline mode, please send me the placeholder message for queries to your bot. People will see this placeholder whenever they type @bot in the message field – in any chat. Tell them what they can get from your bot (e.g., Search GIFs...).

**Comment by aestrada2796** [comment]
https://core.telegram.org/bots/inline.

To enable inline mode, please send me the placeholder message for queries
to your bot. People will see this placeholder whenever they type @bot
<https://github.com/bot> in the message field – in any chat. Tell them what
they can get from your bot (e.g., Search GIFs...).

**Comment by fabio-ivona** [comment]
Ok I got it, will work on it over the next week and will ship and update with these features
