### ISSUE TITLE
[FEAT] Add editMessageCaption endpoint

### ISSUE THREAD

**Issue by alessiovietri** [def-studio/telegraph#96]
Hello everyone,
Thanks a lot for your superb work, this package is amazing.

I just wanted to ask for an enhancement: the `edit()` function provided by the `TelegraphChat` model doesn't work for messages with files. To make it work, I followed these steps (it's working, but I'm not sure if this is the best way to do this):

- added the `editCaption()` function inside the `TelegraphChat` model
- added the `editCaption()` function inside the `ComposesMessages` trait
- added the `ENDPOINT_EDIT_CAPTION` const inside the `Telegraph` class
- updated the `setMessageText()` function inside the `ComposesMessages` trait, adding the line `$this->data['caption'] = $message;` between lines 25 and 26

This works for me, but I think it would be better this way (just as suggestion):
- add a parameter to the `edit()` function -> `edit($messageId, $isCaption = false)`
- add a parameter to the `setMessageText()` function (and related handler) -> `setMessageText($message, $isCaption = false)`

or maybe it would be possible to just add a function that changes the parameter if the message has files attached

Reference:
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1edit_message_caption.html

Thanks a lot in advance!

**Comment by fabio-ivona** [comment]
@alessiovietri thanks for pointing this out, I'll have a look tomorrow and try to sort it out 😉

**Comment by fabio-ivona** [comment]
@alessiovietri this feature will be out in next release :rocket:
