### ISSUE TITLE
[FEAT] Add sendVoice endpoint

### ISSUE THREAD

**Issue by alessiovietri** [def-studio/telegraph#97]
Hello again,
I'm using this amazing package in group chats where are sent a lot of voice recordings. My bot should be able to forward these voices to other chats, but this is not possible at the moment. I've seen through your docs that you're planning to add this feature, but I wanted to share how I made it working:

- added the `ENDPOINT_SEND_VOICE` const inside the `Telegraph` class
- added the `Voice` DTO, copying the already existing `Audio` DTO (I also removed the `thumbnail` property)
- added the `voice()` function inside the `Message` DTO, copying the already existing `audio()` function
- added the `voice()` function inside the `SendsAttachments` trait, copying and editing the already existing `location()` function

I don't remember if it required other steps, but I've done these for sure.

Reference:
https://core.telegram.org/bots/api#sendvoice

Again, thanks a lot in advance!

**Comment by fabio-ivona** [comment]
Hi @alessiovietri send Voice is on our roadmap, but feel free to open a pull request for this feature, if you have a working implementation

Don't worry if it is not perfect,we can refine it together

**Comment by alessiovietri** [comment]
Ok, thanks a lot. I was planning to do it, but (to be honest) I'm not the best with tests
